# Generated by Django 4.0.5 on 2023-05-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=255)),
                ('route_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=255)),
                ('longitude', models.IntegerField(default=0)),
                ('latitude', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
            ],
            options={
                'db_table': 'stop',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField(default=0)),
                ('normal_seats', models.IntegerField(default=0)),
                ('disabled_seats', models.IntegerField(default=0)),
                ('transport_number', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.route')),
            ],
            options={
                'db_table': 'transport',
            },
        ),
        migrations.CreateModel(
            name='Stop_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_in', models.IntegerField(default=0)),
                ('passenger_out', models.IntegerField(default=0)),
                ('timestamp', models.TimeField(default=0)),
                ('cycle_amount', models.IntegerField(default=0)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.stop')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.transport')),
            ],
            options={
                'db_table': 'stop_record',
            },
        ),
        migrations.CreateModel(
            name='Routes_stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('route', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transports.route')),
                ('stop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transports.stop')),
            ],
            options={
                'db_table': 'routes_stops',
            },
        ),
        migrations.CreateModel(
            name='Companies_routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('route', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transports.route')),
            ],
            options={
                'db_table': 'companies_routes',
            },
        ),
    ]
