# Generated by Django 4.0.5 on 2023-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies_routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0)),
                ('route_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=255)),
                ('route_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Routes_stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('route_id', models.IntegerField(default=0)),
                ('stop_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(default=0)),
                ('stop_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stop_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_id', models.IntegerField(default=0)),
                ('stop_id', models.IntegerField(default=0)),
                ('passenger_in', models.IntegerField(default=0)),
                ('passenger_out', models.IntegerField(default=0)),
                ('timestamp', models.TimeField(default=0)),
                ('cycle_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0)),
                ('route_id', models.IntegerField(default=0)),
                ('total_seats', models.IntegerField(default=0)),
                ('normal_seats', models.IntegerField(default=0)),
                ('disabled_seats', models.IntegerField(default=0)),
                ('transport_number', models.CharField(max_length=255)),
            ],
        ),
    ]
