# Generated by Django 4.0.5 on 2023-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stop',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
    ]
