# Generated by Django 4.0.5 on 2023-04-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_company_city_id'),
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies_routes',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='companies_routes',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.route'),
        ),
        migrations.AlterField(
            model_name='routes_stops',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.route'),
        ),
        migrations.AlterField(
            model_name='routes_stops',
            name='stop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.stop'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='stop_record',
            name='stop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.stop'),
        ),
        migrations.AlterField(
            model_name='stop_record',
            name='transport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.transport'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.route'),
        ),
    ]
