# Generated by Django 4.0.5 on 2023-05-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_route_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies_routes',
        ),
    ]
