# Generated by Django 4.0.5 on 2023-04-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_companies_cities_city_id_and_more'),
        ('transports', '0002_alter_companies_routes_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
