# Generated by Django 4.0.5 on 2023-05-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_remove_transport_route_route_transports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='transports',
        ),
        migrations.AddField(
            model_name='transport',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transports.route'),
            preserve_default=False,
        ),
    ]
