# Generated by Django 4.0.5 on 2023-05-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_delete_companies_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop_record',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='has_report',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='is_tracking',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
