# Generated by Django 4.0.5 on 2023-04-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_rename_company_id_companies_routes_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies_routes',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='companies_routes',
            old_name='route',
            new_name='route_id',
        ),
        migrations.RenameField(
            model_name='routes_stops',
            old_name='route',
            new_name='route_id',
        ),
        migrations.RenameField(
            model_name='routes_stops',
            old_name='stop',
            new_name='stop_id',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='stop_record',
            old_name='stop',
            new_name='stop_id',
        ),
        migrations.RenameField(
            model_name='stop_record',
            old_name='transport',
            new_name='transport_id',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='route',
            new_name='route_id',
        ),
    ]
