# Generated by Django 4.0.5 on 2023-05-06 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_stop_record_date_transport_has_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop_record',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 6), null=True),
        ),
    ]
