# Generated by Django 4.0.5 on 2023-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0005_alter_stop_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop_record',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
