# Generated by Django 4.0.5 on 2023-05-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0006_alter_stop_record_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='has_report',
        ),
        migrations.AddField(
            model_name='stop_record',
            name='has_report',
            field=models.BooleanField(default=False),
        ),
    ]
