# Generated by Django 4.0.5 on 2023-05-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0007_remove_transport_has_report_stop_record_has_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stop',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=15),
        ),
    ]
