# Generated by Django 4.0.5 on 2023-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0008_alter_stop_latitude_alter_stop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='passengers_now',
            field=models.IntegerField(default=0),
        ),
    ]
