# Generated by Django 4.0.5 on 2023-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0009_transport_passengers_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='passengers_now',
        ),
        migrations.AddField(
            model_name='stop_record',
            name='passengers_now',
            field=models.IntegerField(default=0),
        ),
    ]
