# Generated by Django 4.0.5 on 2023-04-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies_cities',
            name='city',
        ),
        migrations.AddField(
            model_name='companies_cities',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='companies_cities',
            name='company',
        ),
        migrations.AddField(
            model_name='companies_cities',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
            preserve_default=False,
        ),
    ]
