# Generated by Django 4.0.5 on 2023-04-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_companies_cities_city_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies_cities',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='companies_cities',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='user_id',
            new_name='user',
        ),
    ]
