# Generated by Django 4.0.5 on 2023-04-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_city_id_companies_cities_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies_cities',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='companies_cities',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='user_id',
        ),
    ]
